version: '3.8'

services:
  backend:
    image: todo-backend
    build:
      context: ./backend/ # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    ports:
      - 3003:3003
    container_name: blogs-backend

  frontend:
    image: blogs-frontend
    build:
      context: ./frontend/ # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    ports:
      - 3000:3000
    container_name: blogs-frontend